[package]
name = "rust-memory-layout"
version = "0.1.0"
authors = ["zyq823 <yiqingzhao94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
